### ISSUE TITLE
opening dependency file build/evolver.d: No such file or directory

### ISSUE THREAD

**Issue by ghost** [PaulTOliver/salis#1]
I have the problem, when I try to build salis:

```
~/lab/salis $ sudo make
gcc -Iinclude -c -ggdb -MMD -Wall -Wextra -std=c89 -pedantic-errors -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition src/evolver.c -o build/evolver.o
src/evolver.c:250:1: fatal error: opening dependency file build/evolver.d: No such file or directory
 }
 ^
compilation terminated.
Makefile:25: recipe for target 'build/evolver.o' failed
make: *** [build/evolver.o] Error 1

```
I use Linux Mint on Virtualbox (Windows 10 Host).

**Comment by PaulTOliver** [comment]
Hi.
Try making two new sub-directories inside the salis directory named "build" and "lib".
Can you tell me if this fixes the issue?

**Comment by ghost** [comment]
Yeah, this is it.

Thank you.

```
~/lab/salis $ make
gcc -Iinclude -c -ggdb -MMD -Wall -Wextra -std=c89 -pedantic-errors -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition src/evolver.c -o build/evolver.o
gcc -Iinclude -c -ggdb -MMD -Wall -Wextra -std=c89 -pedantic-errors -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition src/loader.c -o build/loader.o
gcc -Iinclude -c -ggdb -MMD -Wall -Wextra -std=c89 -pedantic-errors -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition src/compiler.c -o build/compiler.o
gcc -Iinclude -c -ggdb -MMD -Wall -Wextra -std=c89 -pedantic-errors -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition src/instset.c -o build/instset.o
gcc -Iinclude -c -ggdb -MMD -Wall -Wextra -std=c89 -pedantic-errors -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition src/memory.c -o build/memory.o
gcc -Iinclude -c -ggdb -MMD -Wall -Wextra -std=c89 -pedantic-errors -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition src/process.c -o build/process.o
gcc -Iinclude -c -ggdb -MMD -Wall -Wextra -std=c89 -pedantic-errors -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition src/salis.c -o build/salis.o
ar rcs lib/libsalis.a build/evolver.o build/loader.o build/compiler.o build/instset.o build/memory.o build/process.o build/salis.o
```

now i have:

```
~/lab/salis/lib $ ls
libsalis.a
```

How to use this library?

**Comment by PaulTOliver** [comment]
You have to build tsalis (https://github.com/PaulTOliver/tsalis) and link it against salis library and ncurses.
That way you can run the simulation. :-)

**Comment by fidergo-stephane-gourichon** [comment]
## Still fails

Xubuntu 18.04 AMD64 here.

> You have to build tsalis (https://github.com/PaulTOliver/tsalis) and link it against salis library and ncurses.
> That way you can run the simulation. :-)

https://github.com/PaulTOliver/tsalis yields 404 not found.

## First, dependency

	sudo apt-get install libncurses-dev

## Are README.md files outdated?

From https://github.com/PaulTOliver/salis/blob/master/tsalis/README.md

> You can also just run the `make` command
> inside the salis directory and it will automate the building and linking of
> both the library and this application.

Let's try

    git clone https://github.com/PaulTOliver/salis
    cd salis/
    cd tsalis/
    make

    gcc -Iinclude -I../include -c -O3 -DNDEBUG -MMD -Wall -Wextra -std=c89 -pedantic-errors -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition src/tsalis.c -o build/tsalis.o
    gcc -Iinclude -I../include -c -O3 -DNDEBUG -MMD -Wall -Wextra -std=c89 -pedantic-errors -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition src/handler.c -o build/handler.o
    gcc -Iinclude -I../include -c -O3 -DNDEBUG -MMD -Wall -Wextra -std=c89 -pedantic-errors -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition src/printer.c -o build/printer.o
    gcc build/tsalis.o build/handler.o build/printer.o -L ../bin -l:libsalis.so -lncurses -o ../bin/tsalis
    /usr/bin/x86_64-linux-gnu-ld: cannot find -l:libsalis.so
    collect2: error: ld returned 1 exit status
    Makefile:21: recipe for target 'all' failed
    make: *** [all] Error 1

## What works for me

    git clone https://github.com/PaulTOliver/salis
    cd salis/
    make
    cd tsalis/
    make
    cd ../bin/
    LD_LIBRARY_PATH=. ./tsalis

My two cents.

**Comment by PaulTOliver** [comment]
Assuming ncurses-dev is installed, this should work on Ubuntu:
```
git clone https://github.com/PaulTOliver/salis
cd salis/
make
sudo make install
```
Apart from a few warnings, this should work on Ubuntu. To run:
```
cd bin/
./tsalis
```
